"""Verify the round-trip on every PRISM-IR example in examples/.

For each .prism.md file:
  1. Load original natural-language description and IR.
  2. Reconstruct natural language from the IR alone via an LLM.
  3. Use an LLM-as-judge call to score whether the reconstruction
     preserves the intent of the original.
  4. Pass if all examples score above threshold; fail otherwise.

Exit codes:
  0 = all examples passed
  1 = at least one example failed
  2 = invocation or environment error

This script is the verification gate the LinkedIn announcement image's
"Deterministic Round-Trip Reconstruction Verified" claim points to.
CI runs it on every push.
"""

import json
import os
import re
import sys
from pathlib import Path

import yaml
from anthropic import Anthropic


RECONSTRUCTION_PROMPT = """You are reading a PRISM-IR file. PRISM-IR is a typed intermediate
representation for processes. Your job is to reconstruct the original
plain-English process description from the IR alone.

Rules:
- Output only the natural-language description. No preamble, no
  commentary, no markdown formatting.
- Match the granularity of a numbered step list, not a paragraph.
- Each numbered step should correspond to a meaningful action or
  decision in the IR.
- Decisions should be expressed as branching language ("if X, then Y;
  otherwise Z").
- Do not invent details that are not in the IR.
- Do not omit details that are in the IR.

PRISM-IR file:

{ir_yaml}

Reconstruct the original natural-language description:"""


JUDGE_PROMPT = """You are evaluating whether a PRISM-IR round-trip preserved process intent.

You will see three artifacts:

1. ORIGINAL — the natural-language process description authored by a human.
2. PRISM-IR — the typed intermediate representation derived from the original.
   This is the structural source of truth: parameters, event payloads,
   action sequences, retry policies, distributions, lifecycle states, and
   resource bindings live here even when the original English elides them.
3. RECONSTRUCTION — natural-language description regenerated by an LLM that
   was shown only the PRISM-IR (not the original).

Score the reconstruction on three dimensions, 0-3 each:

- COMPLETENESS (compare RECONSTRUCTION to ORIGINAL): does the reconstruction
  cover every meaningful step, branch, and consequence the original
  describes?
  3 = every meaningful element of the original is present
  2 = a minor original element is omitted but core flow intact
  1 = a meaningful original step or branch is missing
  0 = significant original content lost

- ACCURACY (compare RECONSTRUCTION to PRISM-IR): does the reconstruction
  avoid inventing content that is NOT encoded in the PRISM-IR? Detail that
  IS in the PRISM-IR (parameter values, retry/escalation policies, event
  emissions, statistical distributions, lifecycle states, vocabulary terms,
  intentions, etc.) is FAIR GAME for the reconstruction to surface even if
  the original English did not mention it. Penalize only content that the
  PRISM-IR does not justify.
  3 = nothing in the reconstruction is absent from the PRISM-IR
  2 = minor harmless restating of PRISM-IR content in reasonable terms
  1 = a detail added that is not in the PRISM-IR
  0 = significant fabrication beyond the PRISM-IR

- BRANCHING (compare RECONSTRUCTION to PRISM-IR's flow graph): are
  conditional paths, decisions, and joins preserved correctly relative to
  the PRISM-IR's edges and decision modes?
  3 = all branches and conditions match the PRISM-IR
  2 = branches preserved with minor wording drift
  1 = a branch swapped, mislabeled, or merged
  0 = branching logic substantially wrong

A reconstruction passes if it scores at least 2 on every dimension.

ORIGINAL:
---
{original}
---

PRISM-IR:
---
{ir_yaml}
---

RECONSTRUCTION:
---
{reconstruction}
---

Respond with a single JSON object on one line, no preamble:
{{"completeness": <0-3>, "accuracy": <0-3>, "branching": <0-3>, "verdict": "pass" or "fail", "reasoning": "<one sentence>"}}"""


def load_prism_file(path):
    text = Path(path).read_text()
    english_match = re.search(
        r"## Natural Language\s*\n(.+?)(?=\n## )",
        text,
        re.DOTALL,
    )
    if not english_match:
        raise ValueError(f"No '## Natural Language' section found in {path}")
    yaml_match = re.search(r"```yaml\s*\n(.+?)\n```", text, re.DOTALL)
    if not yaml_match:
        raise ValueError(f"No ```yaml fenced block found in {path}")
    yaml.safe_load(yaml_match.group(1))
    return english_match.group(1).strip(), yaml_match.group(1).strip()


def reconstruct_english(ir_yaml, client, model):
    response = client.messages.create(
        model=model,
        max_tokens=1024,
        messages=[{"role": "user", "content": RECONSTRUCTION_PROMPT.format(ir_yaml=ir_yaml)}],
    )
    return response.content[0].text.strip()


def judge_reconstruction(original, ir_yaml, reconstruction, client, model):
    response = client.messages.create(
        model=model,
        max_tokens=512,
        messages=[
            {
                "role": "user",
                "content": JUDGE_PROMPT.format(
                    original=original, ir_yaml=ir_yaml, reconstruction=reconstruction
                ),
            }
        ],
    )
    text = response.content[0].text.strip()
    json_match = re.search(r"\{.*\}", text, re.DOTALL)
    if not json_match:
        raise ValueError(f"Judge did not return valid JSON: {text}")
    return json.loads(json_match.group(0))


def verify_example(path, client, model):
    print(f"\n→ {path}")
    original, ir_yaml = load_prism_file(path)
    reconstruction = reconstruct_english(ir_yaml, client, model)
    verdict = judge_reconstruction(original, ir_yaml, reconstruction, client, model)
    scores = (
        f"completeness={verdict['completeness']} "
        f"accuracy={verdict['accuracy']} "
        f"branching={verdict['branching']}"
    )
    status = "PASS" if verdict["verdict"] == "pass" else "FAIL"
    print(f"  {status}  {scores}  ({verdict['reasoning']})")
    return verdict["verdict"] == "pass", verdict, reconstruction


def build_client():
    """Build an Anthropic client. ANTHROPIC_API_KEY may be either an
    `sk-ant-...` console API key or an `oat_...` Claude Code OAuth token;
    the latter is routed through Bearer auth with the OAuth beta header."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        print("error: set ANTHROPIC_API_KEY environment variable", file=sys.stderr)
        sys.exit(2)
    if key.startswith("oat_"):
        return Anthropic(
            auth_token=key,
            default_headers={"anthropic-beta": "oauth-2025-04-20"},
        )
    return Anthropic()


def main():
    model = os.getenv("PRISM_VERIFY_MODEL", "claude-sonnet-4-6")
    examples_dir = Path("examples")
    if not examples_dir.is_dir():
        print("error: examples/ directory not found", file=sys.stderr)
        sys.exit(2)

    files = sorted(examples_dir.glob("*.prism.md"))
    if not files:
        print("error: no .prism.md files found in examples/", file=sys.stderr)
        sys.exit(2)

    client = build_client()
    print(f"Verifying {len(files)} example(s) with {model}...")

    failures = []
    for path in files:
        try:
            ok, _verdict, _recon = verify_example(path, client, model)
            if not ok:
                failures.append(str(path))
        except Exception as exc:
            print(f"  ERROR  {exc}")
            failures.append(str(path))

    print()
    if failures:
        print(f"FAILED: {len(failures)} of {len(files)} examples did not preserve intent:")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    print(f"PASSED: all {len(files)} examples preserved intent under round-trip.")
    sys.exit(0)


if __name__ == "__main__":
    main()
